### ISSUE TITLE
No TXw mask is produced if there are not multiple T1s or T2s

### ISSUE THREAD

**Issue by ericearl** [DCAN-Labs/dcan-macaque-pipeline#2]
According to this chunk of code:
https://github.com/DCAN-Labs/dcan-macaque-pipeline/blob/master/PreFreeSurfer/PreFreeSurferPipeline.sh#L237-L256

If there are multiple T1s or T2s, then produce a mask and other files.  But `else` only copy the T1w or T2w image.  I think this needs to include an `imcp` of the mask as well upon evaluation of the `else` statement..

**Comment by LuciMoore** [comment]
It appears that the issue might have been addressed implicitly through subsequent updates, changes, or improvements. Since there hasn't been any recent activity or confirmation regarding its relevance, we are considering this issue resolved.

If you believe the matter is still relevant or requires further attention, please feel free to reopen the issue, and we'll be more than happy to revisit and address it promptly.
