### ISSUE TITLE
final dtseries output in two places, with multiple names 

### ISSUE THREAD

**Issue by amitch3** [DCAN-Labs/dcan-macaque-pipeline#4]
![image](https://user-images.githubusercontent.com/41393207/89743464-405c7600-da58-11ea-8f8e-103cef85c04a.png)

the dtseries for analysis is in multiple places (see snip above). it is the same file, named different names - probably an easy house cleaning issue

**Comment by ericearl** [comment]
@amitch3 I am guessing you only have one run in this example.  In other cases, the first file in your diff there would be a concatenated file of all runs.  The second file in your diff is, in fact, that single run's DCANBOLDProcessed DTSERIES.  So this behavior is intentional.  I'll close this for now unless you tell me there was actually more than one run.
